# Generated by Django 4.0.5 on 2022-06-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_remove_country_country_id_country_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
