# Generated by Django 4.0.5 on 2022-06-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_flag',
        ),
    ]
