# Generated by Django 4.0.5 on 2022-06-27 19:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='article_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
